apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "transformer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "transformer.name" . }}
    chart: {{ template "transformer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ENVIRONMENT: {{ .Values.ENVIRONMENT }}
  CONFIG__TRANSFORMER_PATH: {{ .Values.CONFIG__TRANSFORMER_PATH }}
