apiVersion: v1
kind: Secret
metadata:
  name: {{ template "transformer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "transformer.name" . }}
    chart: {{ template "transformer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ if .Values.mlflow.mlflow_s3_access_key }} {{ .Values.mlflow.mlflow_s3_access_key | b64enc | quote }} {{ else }} {{ .Values.s3.accessKey | b64enc | quote }} {{ end }}
  AWS_SECRET_ACCESS_KEY: {{ if .Values.mlflow.mlflow_s3_secret_key }} {{ .Values.mlflow.mlflow_s3_secret_key | b64enc | quote }} {{ else }} {{ .Values.s3.secretKey | b64enc | quote }} {{ end }}
