apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "candy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "candy.name" . }}
    chart: {{ template "candy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CANDY_LANGUAGE: {{ .Values.CANDY_LANGUAGE }}
  CANDY_ENVIRONMENT: {{ .Values.CANDY_ENVIRONMENT }}

  CANDY_CANDIDATES_PROVIDERS: {{ .Values.CANDY_CANDIDATES_PROVIDERS | quote }}
  CANDY_CATALOGUE: {{ .Values.CANDY_CATALOGUE | quote }}
  CANDY_FAISS: {{ .Values.CANDY_FAISS | quote }}
  CANDY_ELASTIC_ADDRESS: {{ .Values.CANDY_ELASTIC_ADDRESS | quote }}
  CANDY_ELASTIC_CANDIDATES_INDEX: {{ .Values.CANDY_ELASTIC_CANDIDATES_INDEX | quote }}

  CANDY_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.CANDY_KAFKA_BOOTSTRAP_SERVERS }}
  CANDY_KAFKA_CONSUMER_GROUP_ID: {{ .Values.CANDY_KAFKA_CONSUMER_GROUP_ID }}
  {{ if .Values.CANDY_KAFKA_SASL_USERNAME }}
  CANDY_KAFKA_SASL_USERNAME: {{ .Values.CANDY_KAFKA_SASL_USERNAME }}
  {{ end }}
  {{ if .Values.CANDY_CANDIDATE_REQUIRED_FIELDS }}
  CANDY_KAFKA_SASL_PASSWORD: {{ .Values.CANDY_KAFKA_SASL_PASSWORD }}
  {{ end }}
  CANDY_KAFKA_RETRIES: {{ .Values.CANDY_KAFKA_RETRIES | quote }}
  CANDY_KAFKA_MAX_REQUESTS_PER_CONN: {{ .Values.CANDY_KAFKA_MAX_REQUESTS_PER_CONN | quote }}
  CANDY_KAFKA_CONSUME_MAX_MESSAGES: {{ .Values.CANDY_KAFKA_CONSUME_MAX_MESSAGES | quote }}
  CANDY_KAFKA_CONSUME_TIMEOUT: {{ .Values.CANDY_KAFKA_CONSUME_TIMEOUT | quote }}
  CANDY_KAFKA_CHECK_TOPIC_EXISTENCE: {{ .Values.CANDY_KAFKA_CHECK_TOPIC_EXISTENCE | quote }}

  CANDY_WRITE_RESULTS_TO_MONOLITH: {{ .Values.CANDY_WRITE_RESULTS_TO_MONOLITH | quote }}
  CANDY_TOPIC_REDIS: {{ .Values.CANDY_TOPIC_REDIS }}
  CANDY_TOPIC_KAFKA_CANDIDATE_EMBEDDING: {{ .Values.CANDY_TOPIC_KAFKA_CANDIDATE_EMBEDDING }}
  CANDY_TOPIC_KAFKA_ITEM_MATCHED: {{ .Values.CANDY_TOPIC_KAFKA_ITEM_MATCHED }}
  CANDY_TOPIC_KAFKA_ITEM_NOT_MATCHED: {{ .Values.CANDY_TOPIC_KAFKA_ITEM_NOT_MATCHED }}
  CANDY_TOPIC_KAFKA_ITEM_UNKNOWN: {{ .Values.CANDY_TOPIC_KAFKA_ITEM_UNKNOWN }}
  CANDY_TOPIC_KAFKA_ITEM_NO_CANDIDATES_FOUND: {{ .Values.CANDY_TOPIC_KAFKA_ITEM_NO_CANDIDATES_FOUND }}

  CANDY_MAX_RETRY: {{ .Values.CANDY_MAX_RETRY | quote }}
  CANDY_MAX_MINUTES: {{ .Values.CANDY_MAX_MINUTES | quote }}

  CANDY_ITEMS_RANGE_SIZE: {{ .Values.CANDY_ITEMS_RANGE_SIZE | quote }}
  CANDY_CANDIDATES_LIMIT: {{ .Values.CANDY_CANDIDATES_LIMIT | quote }}
  CANDY_MAX_WEIGHT: {{ .Values.CANDY_MAX_WEIGHT | quote }}
  CANDY_NO_ITEMS_SLEEP: {{ .Values.CANDY_NO_ITEMS_SLEEP | quote }}
  CANDY_EMBEDDING_QUEUE_CHECK_SLEEP: {{ .Values.CANDY_EMBEDDING_QUEUE_CHECK_SLEEP | quote }}
  CANDY_EMBEDDING_READY_TIMEOUT: {{ .Values.CANDY_EMBEDDING_READY_TIMEOUT | quote }}
  CANDY_DISTANCE_THRESHOLD: {{ .Values.CANDY_DISTANCE_THRESHOLD | quote }}
  CANDY_SUPPORTED_CATEGORIES: {{ .Values.CANDY_SUPPORTED_CATEGORIES | quote }}
  CANDY_USE_IMAGESIMILARITY: {{ .Values.CANDY_USE_IMAGESIMILARITY | quote }}
  CANDY_REMOVE_LONGTAIL: {{ .Values.CANDY_REMOVE_LONGTAIL | quote }}

  CANDY_REDIS_OFFERS_ADDRESS: {{ .Values.CANDY_REDIS_OFFERS_ADDRESS }}
  CANDY_REDIS_OFFERS_DB: {{ .Values.CANDY_REDIS_OFFERS_DB | quote }}

  CANDY_REDIS_MONOLITH_MATCHING_ADDRESS: {{ .Values.CANDY_REDIS_MONOLITH_MATCHING_ADDRESS | quote }}
  CANDY_REDIS_MONOLITH_MATCHING_DB: {{ .Values.CANDY_REDIS_MONOLITH_MATCHING_DB | quote }}

  {{ if .Values.CANDY_CANDIDATE_REQUIRED_FIELDS }}
  CANDY_CANDIDATE_REQUIRED_FIELDS: {{ .Values.CANDY_CANDIDATE_REQUIRED_FIELDS }}
  {{ end }}
  {{ if .Values.CANDY_ITEM_REQUIRED_FIELDS }}
  CANDY_ITEM_REQUIRED_FIELDS: {{ .Values.CANDY_ITEM_REQUIRED_FIELDS }}
  {{ end }}

  CANDY_EXTRACT_FILES: {{ .Values.CANDY_EXTRACT_FILES | quote }}

  CANDY_MATCHAPI_BASE: {{ .Values.CANDY_MATCHAPI_BASE | quote }}
  CANDY_MATCHAPI_CONFIG_FILE: {{ .Values.CANDY_MATCHAPI_CONFIG_FILE | quote }}

  CANDY_FEATURE_OC: {{ .Values.FEATURE_OC | quote }}
  CANDY_PRIORITIZE_STATUS: {{ .Values.CANDY_PRIORITIZE_STATUS | quote }}

  CANDY_VAULT_ENABLED: {{ .Values.vault.enabled | quote }}
  CANDY_VAULT_ADDR: {{ .Values.vault.addr | quote }}
  CANDY_VAULT_OC_MOUNT_POINT: {{ .Values.vault.oc_mount_point | quote }}
  CANDY_VAULT_ML_MOUNT_POINT: {{ .Values.vault.ml_mount_point | quote }}
  CANDY_VAULT_KAFKA_PATH: {{ .Values.vault.kafka_path | quote }}
  CANDY_VAULT_REDIS_PATH: {{ .Values.vault.redis_path | quote }}
  CANDY_VAULT_ELASTIC_PATH: {{ .Values.vault.elastic_path | quote }}
  CANDY_VAULT_S3_PATH: {{ .Values.vault.s3_path | quote }}
