apiVersion: v1
kind: Secret
metadata:
  name: {{ template "candy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "candy.name" . }}
    chart: {{ template "candy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CANDY_SENTRY_DSN: {{ .Values.CANDY_SENTRY_DSN | b64enc | quote }}
  CANDY_REDIS_OFFERS_PASSWORD: {{ .Values.CANDY_REDIS_OFFERS_PASSWORD | b64enc | quote }}
  CANDY_REDIS_MONOLITH_MATCHING_PASSWORD: {{ .Values.CANDY_REDIS_MONOLITH_MATCHING_PASSWORD | b64enc | quote }}
  CANDY_VAULT_TOKEN: {{ .Values.vault.token | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.CANDY_AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.CANDY_AWS_SECRET_ACCESS_KEY | b64enc | quote }}
