---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-workflow
  namespace: catalogue-mlflow

---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ml-workflow-edit
    namespace: catalogue-mlflow
  subjects:
  - kind: ServiceAccount
    name: ml-workflow
    namespace: catalogue-mlflow
  roleRef:
    kind: ClusterRole
    name: edit
    apiGroup: rbac.authorization.k8s.io
