# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: registry.gitlab.heu.cz/catalogue/matching-ng/productmatching
  initRepository: registry.gitlab.heu.cz/catalogue/matching-ng/productmatching/init
  tag: a8a036fe378e5fbf85cc541038206b4b36fe5d7a
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

metrics:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  path: /
  hosts:
    - transformer.local

hpa:
  maxReplicas: 8
  minReplicas: 1
  targetCPUUtilizationPercentage: 90

resources:
  limits:
    cpu: 4
    memory: 5Gi
  requests:
    cpu: 1
    memory: 5Gi

volumes:
  dataPath: /app/data/

s3:
  host: s3.heu.cz
  hostBucket: s3.heu.cz
  accessKey: ""
  secretKey: ""
  files: ""

mlflow:
  mlflow_s3_endpoint_url: "https://s3.heu.cz/"
  mlflow_tracking_uri: "http://catalogue-mlflow.stage.k8s.heu.cz/"
  mlflow_tracking_insecure_tls: "true"

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  liveness:
    periodSeconds: 30
    timeoutSeconds: 15
    initialDelaySeconds: 120
    successThreshold: 1
    failureThreshold: 3

LANGUAGE: cz
ENVIRONMENT: stage

feature_flags:
  one_catalogue: false

CONFIG__TRANSFORMER_PATH: "/app/data/sbert_model"
