# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.heu.cz/catalogue/matching-ng/productmatching/auto-monitoring
  initRepository: registry.gitlab.heu.cz/catalogue/matching-ng/productmatching/init
  pullPolicy: Always

resources:
  limits:
    cpu: 1
    memory: 2G
  requests:
    cpu: 1
    memory: 2G

volumes:
  dataPath: /app/data/

s3:
  host: s3.heu.cz
  hostBucket: s3.heu.cz
  accessKey: ""
  secretKey: ""

MATCHAPI_CONFIG_FILE: "s3://matchapi-data-cz/matchapi_id_categories_mapping.json"
MATCHAPI_ALLOW_DISABLE: "false"
TRIGGER_RETRAINING: "false"
MLFLOW_TRACKING_URI: "http://catalogue-mlflow.stage.k8s.heu.cz"

OPSGENIE_API_KEY: ""

LANGUAGE: cz