# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.heu.cz/catalogue/matching-ng/productmatching/matchapi-multi
  initRepository: registry.gitlab.heu.cz/catalogue/matching-ng/productmatching/init
  pullPolicy: Always

resources:
  limits:
    cpu: 10m
    memory: 5M
  requests:
    cpu: 10m
    memory: 5M

volumes:
  dataPath: /app/data/

s3:
  host: s3.heu.cz
  hostBucket: s3.heu.cz
  accessKey: ""
  secretKey: ""
  files: >
    s3://matchapi-data-cz/matchapi_id_categories_mapping.json

LANGUAGE: cz