apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "matchapi-multi.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  IMAGE_TAG: {{ .Values.IMAGE_TAG | quote }}
  TARGET_ENVIRONMENT: {{ .Values.TARGET_ENVIRONMENT }}
  TRIGGER_TOKEN: {{ .Values.TRIGGER_TOKEN | quote }}
  REF: {{ .Values.REF | quote }}
  UNINSTALL: {{ .Values.UNINSTALL | quote }}
  INSTALL: {{ .Values.INSTALL | quote }}
