apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "matchapi-multi.fullname" . }}-configmap-init
  namespace: {{ .Release.Namespace }}
data:
  S3_HOST: {{ .Values.s3.host }}
  S3_HOST_BUCKET: {{ .Values.s3.hostBucket }}
  DATA_PATH: {{ .Values.volumes.dataPath }}
  S3_FILES: {{ .Values.s3.files }}