apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matchapi-multi.fullname" . }}-secret-init
  namespace: {{ .Release.Namespace }}
data:
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc | quote }}