apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "matchapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "matchapi.name" . }}
    chart: {{ template "matchapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "matchapi.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "matchapi.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: init-data-volume
          image: "{{ .Values.image.initRepository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.volumes.dataPath }}
              name: data-volume
          envFrom:
            - configMapRef:
                name: {{ template "matchapi.fullname" . }}-configmap-init
            - secretRef:
                name: {{ template "matchapi.fullname" . }}-secret-init
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python3 
            - /app/SourcesPython/matchapi/main.py
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            httpGet:
              path: /ping
              port: http
          env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

          resources:
{{ toYaml .Values.resources | indent 12 }}
          envFrom:
            - configMapRef:
                name: {{ template "matchapi.fullname" . }}
            - secretRef:
                name: {{ template "matchapi.fullname" . }}
          volumeMounts:
            - mountPath: {{ .Values.volumes.dataPath }}
              name: data-volume
      volumes:
        - name: data-volume
          emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
