apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matchapi.fullname" . }}-secret-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "matchapi.name" . }}
    chart: {{ template "matchapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | b64enc | quote }}